name: soundmates_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  auto_route: ^10.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  shimmer: ^3.0.0
  vector_graphics: ^1.1.18

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.6.5
  vector_graphics_compiler: ^1.1.16

flutter:
  uses-material-design: true
  assets:
    - .env
