name: soundmates_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  beamer: ^1.7.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.21.2
  fpdart: ^1.1.1
  hooks_riverpod: ^2.6.1
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  vector_graphics: ^1.1.18

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.6.5
  vector_graphics_compiler: ^1.1.16

flutter:
  uses-material-design: true
  assets:
    - .env
    - path: assets/images/error.png
    - path: assets/images/background.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/images/onboarding.svg
      transformers:
        - package: vector_graphics_compiler
